- id: doi:10.1038/s41596-022-00726-2
  type: paper
  description: A tutorial plus software package to construct volcano plots easily! Developed at LCMD in EPFL.
  date: 2022-08-17
  image: https://media.springernature.com/w440/springer-static/cover-hires/journal/41596/17/11
  buttons:
    - type: source
      text: Get volcanic!
      link: https://github.com/lcmd-epfl/volcanic
  tags:
    - open science

